export const PRODUCT_LIST_REQUEST = 'PRODUC_LIST_REQUEST'; 
export const PRODUCT_LIST_SUCCESS = 'PRODUC_LIST_SUCCESS'; 
export const PRODUCT_LIST_FAIL = 'PRODUC_LIST_FAIL'; 

export const PRODUCT_DETAIL_REQUEST = 'PRODUC_DETAIL_REQUEST'; 
export const PRODUCT_DETAIL_SUCCESS = 'PRODUC_DETAIL_SUCCESS'; 
export const PRODUCT_DETAIL_FAIL = 'PRODUC_DETAIL_FAIL'; 